name: gmwf
description: "A dispensary management app (offline-first with Firebase)"
publish_to: 'none'

version: 1.4.4

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI & utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.12.0
  dropdown_button2: ^2.3.9
  another_flushbar: ^1.10.24
  fluttertoast: ^9.0.0
  printing: ^5.13.2
  screenshot: ^3.0.0

  # Networking & HTTP
  http: ^1.6.0
  connectivity_plus: ^7.0.0
  share_plus: ^12.0.1
  updater: ^0.2.5

  # State management & reactive
  rxdart: ^0.28.0
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.2

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.4.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  universal_platform: ^1.1.0

  # Misc
  image: ^4.3.0
  crypto: ^3.0.7
  intl: ^0.20.2
  bitsdojo_window: ^0.1.6
  window_manager: ^0.5.1
  excel: ^4.0.6
  archive: ^3.6.1
  pdf: ^3.11.0
  url_launcher: ^6.3.2
  open_filex: ^4.5.0
  file_picker: ^10.3.8
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  croppy: ^1.4.1
  firebase_storage: ^13.0.5
  fl_chart: ^1.1.1
  shimmer: ^3.0.0
  bonsoir: ^6.0.1
  web_socket_channel: ^3.0.3
  network_info_plus: ^7.0.0
  device_info_plus: ^11.3.0
  logger: ^2.6.2


  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  package_info_plus: ^8.2.1
  local_auth: ^2.3.0
  lottie: ^3.3.0
  sentry_flutter: ^8.1.0

  path: any
  collection: any
  flutter_native_splash: any
  arabic_reshaper: ^0.0.1
  motion_tab_bar_v2: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1



flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/gmwf-1.png
  android: true
  ios: true
  web: true
  fullscreen: true
  color_dark: "#041C16"
  image_dark: assets/logo/gmwf-1.png
  
  # Ensure the logo is centered and not stretched
  android_gravity: center
  ios_content_mode: center
  
  android_12:
    image: assets/logo/gmwf-1.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/logo/gmwf-1.png
    icon_background_color_dark: "#041C16"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/gmwf-1.png"

flutter:
  uses-material-design: true
  generate: true
  config:
    enable-swift-package-manager: false

  fonts:
    - family: Noori
      fonts:
        - asset: assets/fonts/NooriNastaliq.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/animations/
    - assets/qr/
    - assets/fonts/
    - assets/Banks Logos/

