// File generated by FlutterFire CLI (manually adjusted for fixes)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux; // ✅ Added Linux instead of throwing error
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA6MmTuZIPIxylV372s8zh-ndbShHwwAk',
    appId: '1:434943069322:web:68564f6ee9d15fe0583173',
    messagingSenderId: '434943069322',
    projectId: 'gmwf-8fc4c',
    authDomain: 'gmwf-8fc4c.firebaseapp.com',
    databaseURL: 'https://gmwf-8fc4c-default-rtdb.firebaseio.com',
    storageBucket: 'gmwf-8fc4c.firebasestorage.app',
    measurementId: 'G-BHP7WLP4SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0DYELVamKSiGZq6OaOa32sQaxmTzyCv8',
    appId: '1:434943069322:android:c1fb7c35d322ca19583173',
    messagingSenderId: '434943069322',
    projectId: 'gmwf-8fc4c',
    databaseURL: 'https://gmwf-8fc4c-default-rtdb.firebaseio.com',
    storageBucket: 'gmwf-8fc4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZOjbX3a2_5eYKi6TZP0W63-EcAb_tOU',
    appId: '1:434943069322:ios:9b5c6c6dd4c84c65583173',
    messagingSenderId: '434943069322',
    projectId: 'gmwf-8fc4c',
    databaseURL: 'https://gmwf-8fc4c-default-rtdb.firebaseio.com',
    storageBucket: 'gmwf-8fc4c.firebasestorage.app',
    iosBundleId: 'com.example.gmwf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRZOjbX3a2_5eYKi6TZP0W63-EcAb_tOU',
    appId: '1:434943069322:ios:9b5c6c6dd4c84c65583173',
    messagingSenderId: '434943069322',
    projectId: 'gmwf-8fc4c',
    databaseURL: 'https://gmwf-8fc4c-default-rtdb.firebaseio.com',
    storageBucket: 'gmwf-8fc4c.firebasestorage.app',
    iosBundleId: 'com.example.gmwf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA6MmTuZIPIxylV372s8zh-ndbShHwwAk',
    appId: '1:434943069322:web:0498250e752846a4583173',
    messagingSenderId: '434943069322',
    projectId: 'gmwf-8fc4c',
    authDomain: 'gmwf-8fc4c.firebaseapp.com',
    databaseURL: 'https://gmwf-8fc4c-default-rtdb.firebaseio.com',
    storageBucket: 'gmwf-8fc4c.firebasestorage.app',
    measurementId: 'G-Y6Z0K32TYK',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDA6MmTuZIPIxylV372s8zh-ndbShHwwAk',
    appId: '1:434943069322:web:linux-fallback', // ✅ placeholder
    messagingSenderId: '434943069322',
    projectId: 'gmwf-8fc4c',
    databaseURL: 'https://gmwf-8fc4c-default-rtdb.firebaseio.com',
    storageBucket: 'gmwf-8fc4c.appspot.com',
  );
}
